In [5]:
import pandas as pd
import numpy as np

In [6]:
df = pd.read_csv("student_performance.csv")
print("dataset loaded succesfully")

dataset loaded succesfully

In [ ]:
df.head()

,student_id,name,age,gender,department,semester,math_score,science_score,english_score,programming_score,attendance_percentage,city,admission_year
0,1001,Aarav Sharma,19,Male,Computer Science,2,85,78,72,91,92,Mumbai,2023
1,1002,Priya Patel,20,Female,Computer Science,2,76,82,88,79,87,Ahmedabad,2023
2,1003,Rohit Verma,19,Male,Electronics,2,65,74,61,55,78,Delhi,2023
3,1004,Sneha Reddy,20,Female,Mechanical,2,70,80,75,48,95,Hyderabad,2023
4,1005,Arjun Nair,19,Male,Computer Science,2,92,88,81,95,90,Kochi,2023

In [ ]:
df.shape

(30, 13)

In [ ]:
print("Columns in the dataset:")
print(df.columns.tolist())

Columns in the dataset:
['student_id', 'name', 'age', 'gender', 'department', 'semester', 'math_score', 'science_score', 'english_score', 'programming_score', 'attendance_percentage', 'city', 'admission_year']

In [ ]:
print("Row indices of the dataset:")
print(df.index.tolist())

Row indices of the dataset:
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29]

In [ ]:
df.describe()

,student_id,age,semester,math_score,science_score,english_score,programming_score,attendance_percentage,admission_year
count,30.000000,30.000000,30.0,30.000000,30.000000,30.000000,30.000000,30.000000,30.0
mean,1015.500000,19.733333,2.0,76.066667,77.833333,74.166667,67.600000,84.500000,2023.0
std,8.803408,0.739680,0.0,11.467896,8.554423,10.003735,21.041175,9.379913,0.0
min,1001.000000,19.000000,2.0,56.000000,61.000000,55.000000,38.000000,65.000000,2023.0
25%,1008.250000,19.000000,2.0,67.250000,71.250000,67.250000,49.250000,77.250000,2023.0
50%,1015.500000,20.000000,2.0,75.500000,78.000000,75.000000,66.000000,86.500000,2023.0
75%,1022.750000,20.000000,2.0,85.750000,83.750000,81.750000,88.750000,91.750000,2023.0
max,1030.000000,21.000000,2.0,95.000000,93.000000,90.000000,97.000000,98.000000,2023.0

In [ ]:
print("Missing values in each column:")
print(df.isnull().sum())

Missing values in each column:
student_id               0
name                     0
age                      0
gender                   0
department               0
semester                 0
math_score               0
science_score            0
english_score            0
programming_score        0
attendance_percentage    0
city                     0
admission_year           0
dtype: int64

In [ ]:
print("Initial missing value:")

In [ ]:
df.loc[df.index[:5],'math_score'] = pd.NA
df.isnull().sum()

student_id               0
name                     0
age                      0
gender                   0
department               0
semester                 0
math_score               5
science_score            1
english_score            1
programming_score        1
attendance_percentage    0
city                     0
admission_year           0
dtype: int64

In [ ]:
print("Missing values after modification:")
print(df.isnull().sum())

Missing values after modification:
student_id               0
name                     0
age                      0
gender                   0
department               0
semester                 0
math_score               1
science_score            1
english_score            1
programming_score        1
attendance_percentage    0
city                     0
admission_year           0
dtype: int64

In [ ]:
print(df["department"].unique())

['Computer Science' 'Electronics' 'Mechanical' 'Civil']

In [ ]:
print(df["department"].value_counts)

<bound method IndexOpsMixin.value_counts of 0     Computer Science
1     Computer Science
2          Electronics
3           Mechanical
4     Computer Science
5          Electronics
6                Civil
7     Computer Science
8           Mechanical
9     Computer Science
10         Electronics
11               Civil
12    Computer Science
13          Mechanical
14    Computer Science
15         Electronics
16               Civil
17    Computer Science
18          Mechanical
19    Computer Science
20         Electronics
21    Computer Science
22               Civil
23          Mechanical
24    Computer Science
25         Electronics
26    Computer Science
27               Civil
28          Mechanical
29    Computer Science
Name: department, dtype: object>

In [ ]:
print(df["department"].value_counts())

Unique values and their counts in the 'department' column:
department
Computer Science    13
Electronics          6
Mechanical           6
Civil                5
Name: count, dtype: int64

In [ ]:
print((df["gender"] == "Male").sum())
print((df["gender"] == "Female").sum())

15
15

In [ ]:
print(df["city"].value_counts())

city
Kochi                 2
Lucknow               2
Thiruvananthapuram    2
Agra                  2
Kolkata               2
Hyderabad             1
Mumbai                1
Delhi                 1
Ahmedabad             1
Varanasi              1
Bangalore             1
Pune                  1
Jaipur                1
Mysore                1
Thrissur              1
Bhopal                1
Chennai               1
Patna                 1
Nagpur                1
Dehradun              1
Chandigarh            1
Surat                 1
Allahabad             1
Kanpur                1
Indore                1
Name: count, dtype: int64

In [ ]:
cs_students = df[df['department'] == 'Computer Science']
print(cs_students[['name','department','city']])

              name        department        city
0     Aarav Sharma  Computer Science      Mumbai
1      Priya Patel  Computer Science   Ahmedabad
4       Arjun Nair  Computer Science       Kochi
7      Divya Singh  Computer Science     Lucknow
9       Ananya Das  Computer Science     Kolkata
12      Suresh Rao  Computer Science      Mysore
14     Ajay Tiwari  Computer Science      Bhopal
17  Swati Kulkarni  Computer Science      Nagpur
19    Nisha Kapoor  Computer Science  Chandigarh
21     Tanvi Mehta  Computer Science       Surat
24       Amit Bose  Computer Science     Kolkata
26   Gaurav Shukla  Computer Science     Lucknow
29  Akanksha Yadav  Computer Science        Agra

In [ ]:
cm = df[df['city'].isin(['Chennai', 'Mumbai'])]
print(cm[['name', 'city', 'programming_score']])

            name     city  programming_score
0   Aarav Sharma   Mumbai                NaN
10   Vikram Iyer  Chennai               72.0

In [ ]:
ch = df[(df['city'] == 'Chennai') | (df['city'] == 'Mumbai')]
print(ch[['name','city','programming_score']])

            name     city  programming_score
0   Aarav Sharma   Mumbai                NaN
10   Vikram Iyer  Chennai               72.0

In [ ]:
low_attendance = df[df['attendance_percentage']<=75]
print(f"Number of students with low percentage:{len(low_attendance)}")
print(low_attendance[['name','department','attendance_percentage']])

Number of students with low percentage:7
             name        department  attendance_percentage
5     Meera Joshi       Electronics                     72
8    Rahul Mishra        Mechanical                     68
14    Ajay Tiwari  Computer Science                     75
16   Manoj Pandey             Civil                     65
20  Harish Pillai       Electronics                     74
22   Sanjay Dubey             Civil                     70
27  Sunita Pillai             Civil                     73

In [ ]:
df['total_score'] = df['math_score'] + df['science_score'] + df['english_score'] + df['programming_score']
top_student = df.loc[df['total_score'].idxmax()]
print("Topper student:")
print(top_student[['name','total_score']])
least_student = df.loc[df['total_score'].idxmin()]
print("\nLeast student:")
print(least_student[['name','total_score']])

Topper student:
name           Ananya Das
total_score         371.0
Name: 9, dtype: object

Least student:
name           Manoj Pandey
total_score           210.0
Name: 16, dtype: object